### ISSUE TITLE
Noticed a Minor Difference between Instructions and Solution

### ISSUE THREAD

**Issue by Lurkerman** [CodeLouisville/May2017-FEWD-Class-Project#1]
In the solution, there is a .wrap div in the header, but the code snippet in Part B of the instructions doesn't have it.  It looks like it should've been there, since the the img line in the instructions seems to be double-indented from the section line.

**Comment by Bumbolio** [comment]
@Lurkerman The wrap div should be in the instructions, it's in the solution.  I've split Challenge 1 into its own branch with the fix and have moved the tag to that branch.  Hope to merge these back into master at some point.
