### ISSUE TITLE
Possible issues with the CSS file.

### ISSUE THREAD

**Issue by CorgiDev** [CodeLouisville/May2017-FEWD-Class-Project#2]
I noticed in the CSS file there is a line-height included that isn't mentioned anywhere in the readme file instructions.

Also in the solution for Challenge 1, there is a spot where the box-sizing attached to the * is nested inside the h1 tag's styling. This appears to be resolved in the Challenge 2 solution, but was not corrected in the Challenge 1 solution.

h1 {
        * {
        box-sizing: border-box;
        }
            font-family: 'Roboto Slab', serif;
            text-transform: uppercase;
            margin: 1em 0;
            font-size: 2.5rem;
        }

**Comment by Bumbolio** [comment]
Thanks @EGrayTech!  Going to fix these issues tonight and re-base the repo.

**Comment by Bumbolio** [comment]
I've branched challenge 1 solution and fixed the bugs in that version.  I have moved the tag for that solution to point at the new branch.  We hope to merge the branches back into master at some point.
